### ISSUE TITLE
a new build (webpack) doesn't work

### ISSUE THREAD

**Issue by e-sailing** [SignalK/simplegauges#7]
The compressed files in dist folder work.
Today I tried to rebuild the files in dist folder with ("npm install" and "npm run watch"). But it doesn't get data anymore. Two or three month ago it worked.
I think a change in the node_modules is the reason.

**Comment by tkurki** [comment]
It worked for me ok, got the data, but I just tweaked the installation procedure and instructions in README a bit. Maybe you can start again from scratch?

Did you remember to connect to for example demo.signalk.org to get data?

**Comment by e-sailing** [comment]
Thank you for your fast reply.
2 hours ago I did a clean install of signalk-server-node "git clone ... npm install bin/nmea-from-file"
Gauges work!
killall node
clear browser cache
I now deleted simplegauges folder
bower install https://github.com/SignalK/simplegauges.git
cd bower../simple..
npm install
npm run build
bin/nmea-from-file
Gauges don't work!

**Comment by e-sailing** [comment]
You are right it does work with demo.signalk.org.
When I change lib/config/config.js line 52 to config.port= env.PORT || 80;
And start sudo bin/nmea-from-file
Gauges work because I don't need to connect to port 3000.
